services:
  - type: static_site
    name: youtube-no-ad-player
    buildCommand: npm ci --legacy-peer-deps && npm run build
    publishPath: build
    envVars:
      - key: NODE_OPTIONS
        value: --max-old-space-size=4096
    routes:
      - type: rewrite
        source: /*
        destination: /index.html