services:
  - type: web
    name: youtube-no-ad-player
    env: static
    buildCommand: npm run render-build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html