services:
  - type: web
    name: youtuber-no-ad
    env: static
    buildCommand: npm run render-build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html